version: '3.8'
services:
  writeguard:
    build: .
    container_name: writeguard-v002
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped